sudo: enabled
dist: xenial
before_install:
  - curl -sL https://noc.one/ubuntu-set-mirror.sh | bash
  - cd $HOME
install:
  - cat $HOME/.bashrc
  - cat $HOME/.bash_profile
  - ls $HOME
script:
  - curl -o- https://raw.githubusercontent.com/SukkaW/dotfiles/master/_install/wsl.sh | bash
